<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Action;
use AppBundle\Entity\Project;
use DateTime;
use Doctrine\ORM\EntityRepository;

/**
 * ActionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActionRepository extends EntityRepository
{
    /**
     * @param Action $action
     *
     * @throws \Doctrine\ORM\OptimisticLockException
     */
    public function persist(Action $action)
    {
        $this->getEntityManager()->persist($action);
        $this->getEntityManager()->flush($action);
    }

    /**
     * Get Actions from project updated since datetime.
     *
     * @param Project  $project
     * @param DateTime $datetime
     *
     * @return array
     */
    public function getUpdatedActions(Project $project, DateTime $datetime)
    {
        return $this->createQueryBuilder('a')
            ->innerJoin('a.item', 'i')
            ->innerJoin('i.project', 'p')
            ->where('p.id = :project')
            ->setParameter('project', $project)
            ->andWhere('a.updated > :updated')
            ->setParameter('updated', $datetime)
            ->getQuery()
            ->getResult();
    }
}
