<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Action;
use Doctrine\ORM\EntityRepository;

/**
 * ActionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActionRepository extends EntityRepository
{
    /**
     * @param Action $action
     *
     * @throws \Doctrine\ORM\OptimisticLockException
     */
    public function persist(Action $action)
    {
        $this->getEntityManager()->persist($action);
        $this->getEntityManager()->flush($action);
    }
}
