services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

#    AppBundle\:
#        resource: '../../src/AppBundle/*'
#        exclude: '../../src/AppBundle/{Entity,Repository}'

    app.repository.user:
        class: AppBundle\Repository\UserRepository
        public: true
        autowire: false
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - AppBundle\Entity\User

    AppBundle\Repository\ActionRepository:
        public: true
        autowire: false
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - AppBundle\Entity\Action

    countdown.repository.item:
        class: AppBundle\Repository\ItemRepository
        public: true
        autowire: false
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - AppBundle\Entity\Item

    countdown.repository.project:
        class: AppBundle\Repository\ProjectRepository
        public: true
        autowire: false
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - AppBundle\Entity\Project

    AppBundle\Services\CountdownService:
        public: true
        autowire: true
        arguments:
            - "@countdown.repository.project"
            - "@countdown.repository.item"
            - '@AppBundle\Repository\ActionRepository'
            - "%app_timezone%"